export const ATOM_KEYS = {
	ALL_TRAVEL_LIST: "ALL_TRAVEL_LIST",

	NOT_SELECTED_TRAVEL_LIST: "NOT_SELECTED_TRAVEL_LIST",
	DONE_TRAVEL_LIST: "DONE_TRAVEL_LIST",
	LOVED_TRAVEL_LIST: "LOVED_TRAVEL_LIST",
} as const;
